version: '3.3'
services:
  sisa:
    build: .
    ports:
      - "81:80"
      #      para não matar minha mudança ao dar docker compose down
    volumes:
      - ./:/usr/share/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
